[package]
name = "sd-graphics"
version = "0.1.0"
authors = ["Nick Hu <me@nickhu.co.uk>", "Alex Rice <alexrice999@hotmail.co.uk>", "Calin Tataru <calintat@gmail.com>"]
edition = "2021"
license = "BSD-3-Clause"
repository = "https://github.com/calintat/sd-visualiser"

[dependencies]
derivative = "2.2.0"
egui = "0.21.0"
good_lp = { version = "1.4.0", default_features = false, features = ["minilp"] }
indexmap = "1.9.3"
itertools = "0.10.5"
pretty = "0.12.1"
sd-core = { path = "../sd-core" }
svg = "0.13.1"
thiserror = "1.0.40"
tracing = "0.1.37"

[dev-dependencies]
cargo-husky = { version = "1.5.0", features = ["precommit-hook", "run-cargo-check", "run-cargo-clippy", "run-cargo-fmt"] }
insta = { version = "1.29.0", features = ["ron"] }
serde = "1.0.160"

[features]
cbc = ["good_lp/coin_cbc"]
