[package]
name = "sd-core"
version = "0.1.0"
authors = ["Nick Hu <me@nickhu.co.uk>", "Alex Rice <alexrice999@hotmail.co.uk>", "Calin Tataru <calintat@gmail.com>"]
edition = "2021"
license = "BSD-3-Clause"
repository = "https://github.com/calintat/sd-visualiser"

[dependencies]
from-pest = "0.3.1"
itertools = "0.10.5"
num = "0.4.0"
pest = "2.5.7"
pest-ast = "0.3.3"
pest_derive = "2.5.7"
pretty = "0.12.1"
slab = "0.4.8"
thiserror = "1.0.40"
tracing = "0.1.37"

[dev-dependencies]
anyhow = "1.0.70"
cargo-husky = { version = "1.5.0", features = ["precommit-hook", "run-cargo-check", "run-cargo-clippy", "run-cargo-fmt"] }
insta = { version = "1.29.0", features = ["ron", "redactions"] }
slab = { version = "0.4.8", features = ["serde"] }
rstest = "0.17.0"
serde = "1.0.160"
