[package]
name = "sd-core"
version = "0.1.0"
authors = ["Nick Hu <me@nickhu.co.uk>", "Alex Rice <alexrice999@hotmail.co.uk>", "Calin Tataru <calintat@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
logos = "0.12.1"
rust-sitter = "0.3.2"

[build-dependencies]
rust-sitter-tool = "0.3.2"
